<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <OutputType>exe</OutputType>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="UnitTest1.fs"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="5.0.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.15.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>

</Project>
